Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(prediction.py:13109): Gdk-CRITICAL **: 10:01:04.160: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Central data read
Staellite data read
satellite data prepared
200 20 10
Traceback (most recent call last):
  File "prediction.py", line 545, in <module>
    X_train = central_both_shuffle[feat_dict[feat]]
NameError: name 'feat_dict' is not defined
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(prediction.py:13261): Gdk-CRITICAL **: 10:06:09.878: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Central data read
Staellite data read
satellite data prepared
200 20 10
[0.00196771 0.00221841 0.00242651 0.00249444 0.00260834 0.00294324
 0.0033246  0.00347625 0.00517757 0.00529444 0.00693702 0.00820797
 0.00838004 0.01361651 0.0166509  0.01863895 0.02041467 0.87522242] [ 7 14  8 16 15 13 17  6  0 10  4  1 12  9  3  5 11  2]
[0.00161201 0.00192772 0.0020178  0.00217166 0.00247638 0.0027067
 0.00303098 0.00436253 0.00475506 0.00627012 0.0073512  0.00764986
 0.00927875 0.01110921 0.01224055 0.01271936 0.02478765 0.88353244] [ 7  8 14 15 16 13 17  6  0 10  4  9  1 12  3  5 11  2]
[0.00216067 0.00219885 0.00242727 0.00248581 0.00270401 0.00278593
 0.00319883 0.00329393 0.00454519 0.00479836 0.00610207 0.00832287
 0.00868752 0.01167223 0.01663544 0.01798081 0.02517982 0.87482038] [ 7 15  8 16 14 17 13  6  0 10  4 12  1  9  3 11  5  2]
[0.00202345 0.00230746 0.00268059 0.00276536 0.00279532 0.00292196
 0.00316335 0.00378004 0.00458712 0.00548268 0.00593871 0.00861921
 0.00915704 0.01080605 0.01425067 0.02266875 0.02473504 0.87131721] [ 7  8 15 14 13 16 17  6 10  4  0  9  1 12  3  5 11  2]
[0.00173787 0.00187847 0.00205058 0.00212386 0.00274526 0.00274785
 0.00290234 0.00301841 0.00461247 0.00508592 0.00607156 0.00720904
 0.00972209 0.01131347 0.01302755 0.01572978 0.0274676  0.88055587] [ 7  8 14 15 13 16  6 17 10  0  4  1  9 12  3  5 11  2]
time =  0.6 minutes
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(prediction.py:13617): Gdk-CRITICAL **: 10:12:17.948: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Central data read
Staellite data read
satellite data prepared
200 20 10
[0.00166489 0.00203464 0.00209465 0.00212183 0.00258548 0.00273272
 0.00291036 0.00360518 0.0039603  0.00517504 0.00877955 0.01014666
 0.01087245 0.01315568 0.01670686 0.01770449 0.02489127 0.86885795] [ 7  8 14 15 16 13 17  6  0 10  4 12  9  1  3  5 11  2]
[0.00163746 0.00205301 0.00207278 0.00212581 0.00257445 0.00274882
 0.00288483 0.0036061  0.0039946  0.00525039 0.00857452 0.01009675
 0.01086091 0.01318087 0.0168198  0.01803419 0.02470708 0.86877763] [ 7  8 14 15 16 13 17  6  0 10  4 12  9  1  3  5 11  2]
[0.00164748 0.00203603 0.00205903 0.00211307 0.00257237 0.00274257
 0.00286306 0.00353977 0.00394199 0.00527777 0.00875806 0.01002754
 0.01105618 0.01323025 0.01660652 0.01896356 0.02469113 0.86787362] [ 7  8 14 15 16 13 17  6  0 10  4 12  9  1  3  5 11  2]
[0.00164802 0.00204744 0.00208717 0.00213375 0.00255518 0.00273921
 0.00288367 0.00363973 0.00399693 0.00529178 0.00865069 0.01000164
 0.0108489  0.01310254 0.01687914 0.01818252 0.02469242 0.86861928] [ 7  8 14 15 16 13 17  6  0 10  4 12  9  1  3  5 11  2]
[0.00166505 0.00206346 0.00208932 0.00212405 0.00259593 0.0027556
 0.0028786  0.00359587 0.00392741 0.00528654 0.0087663  0.01010297
 0.01088445 0.01325216 0.01680552 0.01807706 0.0248283  0.8683014 ] [ 7  8 14 15 16 13 17  6  0 10  4 12  9  1  3  5 11  2]
time =  108.1 minutes
